# syntax=docker/dockerfile:1

## Build
FROM golang AS build
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY *.go *.tmpl ./
RUN go build -o /pxeserver

## Deploy
FROM   ubuntu:22.04
COPY --from=build /pxeserver /pxeserver
EXPOSE 69
EXPOSE 8080
WORKDIR /
# USER nonroot:nonroot
ENTRYPOINT ["/pxeserver"]
